-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 15:08:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema facebook_saver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema facebook_saver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `facebook_saver` DEFAULT CHARACTER SET utf8 ;
USE `facebook_saver` ;

-- -----------------------------------------------------
-- Table `facebook_saver`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `facebook_saver`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` VARCHAR(31) NOT NULL,
  `page` VARCHAR(45) NULL,
  `story` TEXT NULL,
  `message` MEDIUMTEXT NULL,
  `created_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `post_id_UNIQUE` (`post_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
